export const events = [
  {
    id: "event-1",
    title: "Kariyer Günleri 2026",
    category: "Seminer",
    date: "12-10-2026",
    time: "14:00",
    location: "A Blok Konferans Salonu",
    description: "Sektörden konuşmacılarla staj ve iş fırsatları üzerine söyleşi.",
    capacity: 120,
  },
  {
    id: "event-2",
    title: "Robotik Atölyesi",
    category: "Atölye",
    date: "20-10-2026",
    time: "10:00",
    location: "Lab 2",
    description: "Sensör ve motor kontrolüyle basit bir robot kolu kurulumu.",
    capacity: 20,
  },
  {
    id: "event-3",
    title: "Siber Güvenlik Söyleşisi",
    category: "Söyleşi",
    date: "27-10-2026",
    time: "13:00",
    location: "B Blok",
    description: "Güncel siber tehditler ve korunma yolları üzerine söyleşi.",
    capacity: 50,
  },
  {
    id: "event-4",
    title: "Web Tasarım Atölyesi",
    category: "Atölye",
    date: "03-11-2026",
    time: "15:00",
    location: "Lab 1",
    description: "HTML ve CSS ile ilk kişisel sayfanı yap.",
    capacity: 30,
  },
  {
    id: "event-5",
    title: "Yapay Zekâ Semineri",
    category: "Seminer",
    date: "10-11-2026",
    time: "14:00",
    location: "A Blok Konferans Salonu",
    description: "Makine öğrenmesinin temelleri ve kampüsteki projeler.",
    capacity: 100,
  },
  {
    id: "event-6",
    title: "Kodlama Yarışması",
    category: "Yarışma",
    date: "21-11-2026",
    time: "09:30",
    location: "Lab 1",
    description: "Takımlar hâlinde algoritma sorularını çözme yarışması.",
    capacity: 40,
  },
];
